### ISSUE TITLE
502 Bad Gateway on Website

### ISSUE THREAD

**Issue by Juliandev02** [modoboa/modoboa-installer#394]
* Distribution: Debian GNU/Linux 11 Bullseye

I'ved recently installed Modoboa on my Server. 
So, i visited the Mail-page... aaand it says ...

502 Bad Gateway
nginx/1.18.0

![image](https://user-images.githubusercontent.com/81520713/134573791-cb6ef47c-77e1-480f-a42b-732116e630b7.png)

i dont know why this happend. i'ved installed modoboa on a clean Linux Server
Can someone help me? 

Commands i'ved used:
./run.py --interactive --debug my-domain.xyz

certbot certonly -d my-domain.xyz
> 2

service nginx restart

/etc/init.d/dovecot restart

**Comment by tonioo** [comment]
@Juliandev02 Would be easier to analyze with the debug trace of your installation

**Comment by Juliandev02** [comment]
> @Juliandev02 Would be easier to analyze with the debug trace of your installation

what do you mean?

**Comment by ilovefreesw** [comment]
Getting same error...

![Screenshot from 2021-09-27 15-06-39](https://user-images.githubusercontent.com/77317006/134884015-4c396c0b-5574-43a8-a6cf-e52c967726f9.png)

**Comment by ilovefreesw** [comment]
Re ran the installer with debug option and logs are here: https://paste.ee/p/Ryx5g

**Comment by ilovefreesw** [comment]
I'll give it another try tomorrow and will report.

**Comment by ilovefreesw** [comment]
> It looks like the feedparser dependency used by Modoboa 1.17.0 is not compatible with python 3.9... I suggest you try the beta release.

I downgraded the Python version to 3.7.8 and changed the database to MySQL. It still shows the same error.

Logs: https://paste.ee/p/wj656

**Comment by tonioo** [comment]
According to the trace, you're still using python3.9

**Comment by ilovefreesw** [comment]
Idk what's happening. I used Pyenv and set 3.7.8 as global version. Even `python3` brings the 3.7.8 shell.

![Screenshot from 2021-09-30 15-24-08](https://user-images.githubusercontent.com/77317006/135430830-1578484a-bf94-4b4c-9601-7d2b61144fba.png)

**Comment by tonioo** [comment]
Try to manually remove the virtualenv created previously (/srv/modoboa/env)

**Comment by ilovefreesw** [comment]
Same result.... it is still using 3.9.... and I can't remove 3.9 completely and replace with 3.7 as it will break the Ubuntu 20.04.

**Comment by tonioo** [comment]
What is the command line you use to launch the installer?

**Comment by ilovefreesw** [comment]
I run the command `sudo ./run.py --debug domain.com` in a virtual environment created using Pthon3.7.8. But it's still using Python3.9.....and I have given up. It is so much pain installing this.... :{}

**Comment by ilovefreesw** [comment]
To make installation smoother, I'll suggest releasing an Amazon Linux AMI or Docker image.

**Comment by Juliandev02** [comment]
> It looks like the feedparser dependency used by Modoboa 1.17.0 is not compatible with python 3.9... I suggest you try the beta release.

which "Beta" release?

**Comment by Juliandev02** [comment]
do u mean this? 
![image](https://user-images.githubusercontent.com/81520713/135722618-50bbc336-ee84-4a77-9376-6249310f1658.png)

**Comment by ilovefreesw** [comment]
> do u mean this? ![image](https://user-images.githubusercontent.com/81520713/135722618-50bbc336-ee84-4a77-9376-6249310f1658.png)

Yes. I think.

**Comment by tonioo** [comment]
@Juliandev02 yes, I'm talking about this option

**Comment by Meseira** [comment]
I had the same problem with Debian bullseye but the option `--beta` solves it for install only. The installed system does not appear to be fully functional.

For example, it is not possible to change the admin password (the interface does not react when clicking on the Update button in Settings/Profile). The browser console throws:
```
POST https://****.*******.***/user/profile/ 502 (Bad Gateway)
```

**Comment by Juliandev02** [comment]
> I had the same problem with Debian bullseye but the option `--beta` solves it for install only. The installed system does not appear to be fully functional.
> 
> For example, it is not possible to change the admin password (the interface does not react when clicking on the Update button in Settings/Profile). The browser console throws:
> 
> ```
> POST https://****.*******.***/user/profile/ 502 (Bad Gateway)
> ```

uh yeah... i want a fully functionally system and not an unstable buggy heh... xd 

so i'd rather wait a bit. maybe someone still has tips on how to install modoboa so that it works. if i install modoboa once and it doesn't work, i can reset my server, and that sucks. 
sooo.... i wait until modoboa stable works fine

**Comment by Meseira** [comment]
Same thing here, not want to tinker with a buggy stuff. I downgraded the system to Debian buster where Python version is 3.7.3 and Modoboa installer works like a charm.

**Comment by ilovefreesw** [comment]
After installing it on Debian 10 that has Python 3.7 built-in...getting 500 server error. Can't create a domain.

https://github.com/modoboa/modoboa/issues/2304#issuecomment-934341775

**Comment by ilovefreesw** [comment]
This is what I see in console. 
![image](https://user-images.githubusercontent.com/77317006/136023497-2c501999-81a0-4c00-a23b-fef4c2a8ea33.png)

**Comment by tonioo** [comment]
Try to remove the virtualenv folder created by previous attempts (/srv/modoboa/env folder) and to run the installer once again using the --beta and --debug flags.

**Comment by ilovefreesw** [comment]
@Juliandev02 What you are going to use it for? I'll say go for some other mail servers, such as  Mailcow or Mail-in-a-Box. They have much better installation and painless configiration.

**Comment by hjri** [comment]
here's your further activity:

bunp

**Comment by rheinon** [comment]
Debial 11 install was fixed in the beta.  It is working fine on mine.  The only issue I can see is the new interface that you can try.  It is not as elegant as the current version.  The blue color is too bright.  Characters are either very large or very small.  I hope it will be fixed in the final version.

**Comment by buzzra** [comment]
Since the last beta release was on Sept. 22 2021 and this incident was opened on Sept 23 2021, basically NOTHING has been done, right? It is now Jan 30th 2022 ANY word on a new version anytime soon? Also, why does the README.rst file claim the installer was tested on Debian 11?

**Comment by JeremyForsythe** [comment]
The issue has not been resolved.  With a clean install of Debian 11 Bullseye and following the installer's directions we are getting the 502 issue.  We will not being using Modaboa because you have not fixed the installer.  If the installer is not being maintained then it implies your software is not being maintained as well.  You are likely loosing a lot of potential customers for your support services due to this one issue alone.

**Comment by svcru** [comment]
why is the issue closed again?
today is February 4, 2023, the problem is still not solved. Still 502 bad gateway

**Comment by tonioo** [comment]
@svcru Please make sure you installer copy is up-to-date. I've just tried a fresh install on a clean Debian 11 system and it is working as expected. If it's still not working, feel free to open a new issue with a complete description.

**Comment by sacb2** [comment]
Hi, i install this in a clean debian 11 and found two problems maybe can help you ...

First ... the nginx fails because the creation of certs fail ... so i run this:
certbot certonly --standalone -d mail.example.com

and then i found the permission are not right on this socket so run this:

sudo chown www-data:www-data /run/uwsgi/app/modoboa_instance/socket
chmod 770 /run/uwsgi/app/modoboa_instance/socket

and finally i firts try to install this on a mysql database but i encounter a problem on the rout that create the users bur i reinstall it using the postgres database and the userrs run well :)
